language: python

python:
  - 2.7

env:
  global:
    - secure: "WfktJm8VQZGirAXuCbi7Y4YxmQoezspIM+NV3H0WVfNR8b7GBR+luRWYpZbCxujuvvkqYoJDU0zaNvbhEZk2RjkHaia1h5H/hhvukQzWFcB3i+IQwr+xDW33A5cHoSsgfrD+cuLl+6r1s/AxIQ540/eqibLb7bdtjYS5BmIDWp0="


before_script:
  - pip install -r requirements.txt
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g mocha
  - npm install
  - bower install

script:
  - grunt
  - mocha static/test
  - python main.py build

after_success:
  - git clone --depth 1 --quiet https://${GH_TOKEN}@github.com/if1live/new-life.git output
  - cd output
  - git checkout gh-pages
  - cp -R ../build/* .
  - git add -f .
  - git commit -a -m "add new site content"
  - git push https://${GH_TOKEN}@github.com/if1live/new-life.git gh-pages --quiet

branches:
  only:
    - master

notifications:
  email: false
